<x-layouts::app :title="__('Archive Acceptance')"><div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-4 md:p-8">
<header><p class="text-sm text-emerald-300">Owner-only / controlled archive acceptance</p><h1 class="text-3xl font-semibold text-white">Archive acceptance and original promotion</h1><p class="mt-2 text-zinc-400">Accept one eligible retained photo at a time. Every original copy is no-overwrite and SHA-256 verified.</p></header>
<section class="rounded-xl border border-amber-700 bg-amber-950/30 p-5 text-amber-100"><strong>Original-preservation boundary:</strong> promotion copies from quarantine into <code>archive_originals</code>. It never moves or deletes the source, overwrites an existing original, creates derivatives or exposes an original download.</section>
<section class="overflow-hidden rounded-xl border border-zinc-700 bg-zinc-900"><div class="border-b border-zinc-700 px-5 py-4"><h2 class="text-xl font-semibold text-white">Eligible retained photos</h2><p class="text-sm text-zinc-400">{{ $eligible->count() }} upload(s)</p></div><div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-sm"><thead class="bg-zinc-800 text-zinc-400"><tr><th class="p-4">Upload</th><th>Duplicate status</th><th>Bytes</th><th>Dimensions</th><th>SHA-256</th><th>Archive link</th></tr></thead><tbody>
@forelse($eligible as $upload)<tr class="border-t border-zinc-700"><td class="p-4"><a class="text-emerald-300" href="{{ route('admin.archive-promotions.show', $upload) }}">{{ $upload->upload_id }}</a></td><td>{{ $upload->duplicate_status->value }}</td><td>{{ number_format($upload->file_size_bytes) }}</td><td>{{ $upload->width }} × {{ $upload->height }}</td><td><code>{{ substr((string)$upload->sha256,0,12) }}…{{ substr((string)$upload->sha256,-8) }}</code></td><td>null</td></tr>@empty<tr><td colspan="6" class="p-8 text-zinc-400">No eligible retained photos.</td></tr>@endforelse
</tbody></table></div></section>
<section class="overflow-hidden rounded-xl border border-zinc-700 bg-zinc-900"><div class="border-b border-zinc-700 px-5 py-4"><h2 class="text-xl font-semibold text-white">Promoted originals</h2><p class="text-sm text-zinc-400">{{ $promoted->count() }} promotion(s)</p></div><div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-sm"><thead class="bg-zinc-800 text-zinc-400"><tr><th class="p-4">Upload</th><th>Archive ID</th><th>Original disk</th><th>Bytes</th><th>Quarantine retained</th></tr></thead><tbody>
@forelse($promoted as $promotion)<tr class="border-t border-zinc-700"><td class="p-4"><a class="text-emerald-300" href="{{ route('admin.archive-promotions.show', $promotion->incoming_upload_id) }}">{{ $promotion->incomingUpload->upload_id }}</a></td><td>{{ $promotion->mediaItem->archive_id }}</td><td>{{ $promotion->originalVersion->storage_disk }}</td><td>{{ number_format($promotion->target_bytes) }}</td><td>true</td></tr>@empty<tr><td colspan="5" class="p-8 text-zinc-400">No archive promotions yet.</td></tr>@endforelse
</tbody></table></div></section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-5"><h2 class="font-semibold text-white">Blocked intake remains untouched</h2><p class="mt-2 text-zinc-400">{{ $blocked->count() }} retained upload(s) are blocked by duplicate state, missing facts, missing source integrity or an existing archive link.</p><p class="mt-2 text-sm text-zinc-500">No bulk approval, delete, cleanup, derivative or original-download action exists.</p></section>
</div></x-layouts::app>