<x-layouts::app :title="__('Archive Acceptance Review')"><div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-4 md:p-8">
<header><p class="text-sm text-emerald-300">Owner-only / one retained photo</p><h1 class="text-3xl font-semibold text-white">{{ $upload->upload_id }}</h1><p class="mt-2 text-zinc-400">Controlled archive acceptance review</p></header>
@if(session('status'))<section class="rounded-xl border border-emerald-700 bg-emerald-950/30 p-5 text-emerald-100">{{ session('status') }}</section>@endif
<section class="rounded-xl border border-amber-700 bg-amber-950/30 p-5 text-amber-100"><strong>Permanent preservation warning:</strong> the quarantine source remains retained. Promotion never moves or deletes it, overwrites an existing original, generates derivatives or exposes an original download.</section>
<section class="grid gap-4 lg:grid-cols-2"><article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Eligibility and source integrity</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Media type</dt><dd>{{ $upload->media_type->value }}</dd><dt class="text-zinc-500">Retained</dt><dd>{{ $upload->source_file_retained ? 'true' : 'false' }}</dd><dt class="text-zinc-500">Duplicate status</dt><dd>{{ $upload->duplicate_status->value }}</dd><dt class="text-zinc-500">Eligible statuses</dt><dd>{{ implode(', ', $eligibleStatuses) }}</dd><dt class="text-zinc-500">Exact bytes</dt><dd>{{ number_format($upload->file_size_bytes) }}</dd><dt class="text-zinc-500">Dimensions</dt><dd>{{ $upload->width }} × {{ $upload->height }}</dd><dt class="text-zinc-500">SHA-256</dt><dd class="break-all">{{ $upload->sha256 }}</dd><dt class="text-zinc-500">Archive link</dt><dd>{{ $upload->media_item_id ?? 'null' }}</dd></dl></article>
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Quarantine evidence</h2><p class="mt-4 text-zinc-400">Logical disk</p><code class="text-emerald-300">archive_quarantine</code><p class="mt-4 text-zinc-400">Relative path</p><code class="break-all">{{ $upload->incoming_path }}</code><p class="mt-5 text-emerald-200"><strong>source_file_retained=true</strong></p><p class="mt-2 text-zinc-400">The path and bytes remain unchanged after successful promotion.</p></article></section>
@if($promotion)
<section class="grid gap-4 lg:grid-cols-2"><article class="rounded-xl border border-emerald-700 bg-emerald-950/20 p-6"><h2 class="text-xl font-semibold text-white">Accepted MediaItem</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-400">Archive ID</dt><dd>{{ $promotion->mediaItem->archive_id }}</dd><dt class="text-zinc-400">Media type</dt><dd>{{ $promotion->mediaItem->media_type->value }}</dd><dt class="text-zinc-400">Review status</dt><dd>{{ $promotion->mediaItem->review_status->value }}</dd><dt class="text-zinc-400">Approved by</dt><dd>{{ $promotion->actor->name }}</dd><dt class="text-zinc-400">Approved at</dt><dd>{{ $promotion->promoted_at }}</dd><dt class="text-zinc-400">File path on MediaItem</dt><dd>none</dd></dl></article>
<article class="rounded-xl border border-emerald-700 bg-emerald-950/20 p-6"><h2 class="text-xl font-semibold text-white">Verified original MediaFileVersion</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-400">Version type</dt><dd>{{ $promotion->originalVersion->version_type->value }}</dd><dt class="text-zinc-400">Disk</dt><dd>{{ $promotion->target_disk }}</dd><dt class="text-zinc-400">Relative path</dt><dd class="break-all">{{ $promotion->target_path }}</dd><dt class="text-zinc-400">Source / target bytes</dt><dd>{{ number_format($promotion->source_bytes) }} / {{ number_format($promotion->target_bytes) }}</dd><dt class="text-zinc-400">Source SHA-256</dt><dd class="break-all">{{ $promotion->source_sha256 }}</dd><dt class="text-zinc-400">Target SHA-256</dt><dd class="break-all">{{ $promotion->target_sha256 }}</dd><dt class="text-zinc-400">Generation status</dt><dd>{{ $promotion->originalVersion->generation_status->value }}</dd><dt class="text-zinc-400">Derivatives</dt><dd>none</dd></dl></article></section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Immutable promotion audit</h2><p class="mt-3 text-zinc-300">Actor: {{ $promotion->actor->name }} · {{ $promotion->promoted_at }}</p><p class="mt-2 text-emerald-200">Source, written, stored and database byte counts match. Source and target SHA-256 values are identical.</p></section>
@else
<section class="rounded-xl border {{ $eligible ? 'border-emerald-700' : 'border-red-800' }} bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Acceptance decision</h2>
@if($eligible)<p class="mt-3 text-emerald-200">Eligible: all retained-source, technical, duplicate-review and integrity checks pass.</p><form method="POST" action="{{ route('admin.archive-promotions.store', $upload) }}" class="mt-5">@csrf<button class="rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white">Accept and verify original</button></form>
@else<p class="mt-3 text-red-300">Not eligible. Promotion fails closed and no archive object or database record will be created.</p>@endif
</section>
@endif
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Actions that do not exist</h2><p class="mt-3 text-zinc-400">No original download, delete, cleanup, replace, overwrite, derivative-generation, public URL, bulk approval or alternate-source attachment control exists.</p></section>
</div></x-layouts::app>