<x-layouts::app title="Migration Qualification">
<main class="mx-auto min-w-0 max-w-7xl space-y-7 overflow-x-hidden p-6">
    <header class="flex min-w-0 flex-wrap items-end justify-between gap-4">
        <div class="min-w-0"><p class="text-sm font-semibold text-emerald-300">Synthetic scale proof · private migration still separate</p><h1 class="mt-1 text-3xl font-semibold text-white">30,000-file migration qualification</h1><p class="mt-2 max-w-3xl text-zinc-400">Exercise durable checkpoints, forced interruption, idempotent replay, exception recovery and end-to-end reconciliation before any real family source is touched.</p></div>
        <div class="flex flex-wrap gap-3"><a href="{{ route('admin.batch-imports') }}" class="rounded-xl border border-zinc-700 px-4 py-3 text-sm font-semibold text-white">Migration preflight</a><span class="rounded-xl border border-emerald-800 bg-emerald-950/30 px-4 py-3 text-sm text-emerald-100">v{{ config('release.version') }} · {{ config('release.name') }}</span></div>
    </header>

    @if($focused)
        @php($profile = $focused->qualification_profile)
        @php($reconciliation = $profile['reconciliation'] ?? [])
        @php($progress = $focused->target_count > 0 ? min(100, (int) round(($focused->completed_count / $focused->target_count) * 100)) : 0)
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
            <article class="rounded-xl border border-emerald-800 bg-emerald-950/20 p-5"><p class="text-xs uppercase tracking-wide text-emerald-300">Qualification</p><p class="mt-2 text-2xl font-semibold text-white">{{ str($focused->state)->title() }}</p><p class="mt-1 text-sm text-zinc-400">Synthetic harness only</p></article>
            <article class="rounded-xl border border-zinc-700 bg-zinc-900 p-5"><p class="text-xs uppercase tracking-wide text-zinc-500">Manifest</p><p class="mt-2 text-2xl font-semibold text-white">{{ number_format($focused->target_count) }}</p><p class="mt-1 text-sm text-zinc-400">Deterministic entries</p></article>
            <article class="rounded-xl border border-zinc-700 bg-zinc-900 p-5"><p class="text-xs uppercase tracking-wide text-zinc-500">Checkpoints</p><p class="mt-2 text-2xl font-semibold text-sky-300">{{ number_format($focused->checkpoint_count) }}</p><p class="mt-1 text-sm text-zinc-400">{{ number_format($focused->chunk_size) }} entries each</p></article>
            <article class="rounded-xl border border-zinc-700 bg-zinc-900 p-5"><p class="text-xs uppercase tracking-wide text-zinc-500">Recovered</p><p class="mt-2 text-2xl font-semibold text-amber-300">{{ number_format($focused->recovered_failures) }}</p><p class="mt-1 text-sm text-zinc-400">Injected exceptions</p></article>
            <article class="rounded-xl border border-zinc-700 bg-zinc-900 p-5"><p class="text-xs uppercase tracking-wide text-zinc-500">Missing</p><p class="mt-2 text-2xl font-semibold text-emerald-300">{{ number_format($reconciliation['missing'] ?? 0) }}</p><p class="mt-1 text-sm text-zinc-400">After reconciliation</p></article>
        </section>

        <section id="recovery" class="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]">
            <article class="rounded-2xl border border-zinc-700 bg-zinc-900 p-6">
                <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-violet-300">Interruption and resume</p><h2 class="mt-1 text-xl font-semibold text-white">Recovery proof</h2></div><span class="rounded-full border border-emerald-700 bg-emerald-950/30 px-3 py-1 text-xs font-semibold text-emerald-200">{{ $progress }}% reconciled</span></div>
                <div class="mt-5 h-3 overflow-hidden rounded-full bg-zinc-800"><div class="h-full bg-emerald-500" style="width:{{ $progress }}%"></div></div>
                <dl class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-xl bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Forced restarts</dt><dd class="mt-1 text-xl font-semibold text-white">{{ $focused->restart_count }}</dd></div><div class="rounded-xl bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Isolated failures</dt><dd class="mt-1 text-xl font-semibold text-white">{{ $focused->isolated_failures }}</dd></div><div class="rounded-xl bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Recovered safely</dt><dd class="mt-1 text-xl font-semibold text-emerald-300">{{ $focused->recovered_failures }}</dd></div><div class="rounded-xl bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Replay skips</dt><dd class="mt-1 text-xl font-semibold text-sky-300">{{ number_format($focused->duplicate_skips) }}</dd></div></dl>
                <p class="mt-5 rounded-lg border border-zinc-800 bg-zinc-950 p-4 text-sm text-zinc-300">The run stopped after durable checkpoints, restarted from the first pending entry, recovered isolated failures and rejected a replay sample without adding duplicate manifest records.</p>
            </article>
            <aside id="boundary" class="rounded-2xl border border-amber-800 bg-amber-950/20 p-6"><p class="text-sm font-semibold text-amber-300">Claim boundary</p><h2 class="mt-1 text-xl font-semibold text-white">What this proves</h2><ul class="mt-4 space-y-3 text-sm text-amber-100"><li>30,000 persisted manifest entries.</li><li>Bounded, durable checkpoint progression.</li><li>Resume after an injected interruption.</li><li>Idempotent replay protection.</li><li>Complete position and digest reconciliation.</li><li>No real source media or source paths used.</li></ul></aside>
        </section>

        <section id="reconciliation" class="rounded-2xl border border-zinc-700 bg-zinc-900 p-6">
            <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-sky-300">Final accounting</p><h2 class="mt-1 text-xl font-semibold text-white">Checkpoint and integrity reconciliation</h2><p class="mt-1 text-sm text-zinc-400">Expected positions, persisted positions, manifest digest and checkpoint coverage must all agree.</p></div><span class="rounded-full border {{ ($reconciliation['manifest_match'] ?? false) ? 'border-emerald-700 text-emerald-200' : 'border-red-700 text-red-200' }} px-3 py-1 text-xs font-semibold">{{ ($reconciliation['manifest_match'] ?? false) ? 'Manifest matched' : 'Mismatch' }}</span></div>
            <dl class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div class="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Expected</dt><dd class="mt-2 text-xl font-semibold text-white">{{ number_format($reconciliation['expected'] ?? $focused->target_count) }}</dd></div><div class="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Observed</dt><dd class="mt-2 text-xl font-semibold text-white">{{ number_format($reconciliation['observed'] ?? $focused->completed_count) }}</dd></div><div class="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Missing</dt><dd class="mt-2 text-xl font-semibold text-emerald-300">{{ number_format($reconciliation['missing'] ?? 0) }}</dd></div><div class="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Unexpected</dt><dd class="mt-2 text-xl font-semibold text-emerald-300">{{ number_format($reconciliation['unexpected'] ?? 0) }}</dd></div><div class="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><dt class="text-sm text-zinc-500">Coverage</dt><dd class="mt-2 text-xl font-semibold text-emerald-300">{{ ($reconciliation['checkpoint_match'] ?? false) ? 'Complete' : 'Review' }}</dd></div></dl>
        </section>

        <section id="checkpoints" class="rounded-2xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Latest durable checkpoints</h2><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($checkpoints as $checkpoint)<article class="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><div class="flex justify-between gap-3"><strong class="text-white">Checkpoint {{ $checkpoint->checkpoint_number }}</strong><span class="text-xs text-emerald-300">Durable</span></div><p class="mt-2 text-sm text-zinc-400">Positions {{ number_format($checkpoint->first_position) }}–{{ number_format($checkpoint->last_position) }}</p><p class="mt-1 text-xs text-zinc-500">{{ number_format($checkpoint->item_count) }} entries · {{ $checkpoint->exception_count }} exceptions</p></article>@endforeach</div></section>
    @else
        <section class="rounded-2xl border border-dashed border-zinc-700 p-8 text-zinc-400">No migration qualification run has been recorded. Run <code class="text-emerald-300">archive:qualify-migration</code> with an approved operator.</section>
    @endif
</main>
</x-layouts::app>
