<x-layouts::app :title="__('Exact Match Candidate Detail')">
<div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-4 md:p-8">
<header><p class="text-sm text-emerald-300">Owner-only / read-only candidate</p><h1 class="text-3xl font-semibold text-white">DC-{{ str_pad((string)$candidate->id, 6, '0', STR_PAD_LEFT) }}</h1><p class="mt-2 text-amber-200">Possible exact duplicate — manual review required.</p></header>
<section class="grid gap-4 lg:grid-cols-2">
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Source upload</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Upload ID</dt><dd><a class="text-emerald-300" href="{{ route('admin.photo-intake.show', $candidate->incomingUpload) }}">{{ $candidate->incomingUpload->upload_id }}</a></dd><dt class="text-zinc-500">Retained</dt><dd>{{ $candidate->incomingUpload->source_file_retained ? 'true' : 'false' }}</dd><dt class="text-zinc-500">Duplicate status</dt><dd>{{ $candidate->incomingUpload->duplicate_status->value }}</dd><dt class="text-zinc-500">Review status</dt><dd>{{ $candidate->incomingUpload->review_status->value }}</dd></dl></article>
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Exact-match target</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Target type</dt><dd>{{ $candidate->targetType() }}</dd>@if($candidate->matchedIncomingUpload)<dt class="text-zinc-500">Upload ID</dt><dd><a class="text-emerald-300" href="{{ route('admin.photo-intake.show', $candidate->matchedIncomingUpload) }}">{{ $candidate->matchedIncomingUpload->upload_id }}</a></dd><dt class="text-zinc-500">Retained</dt><dd>{{ $candidate->matchedIncomingUpload->source_file_retained ? 'true' : 'false' }}</dd>@else<dt class="text-zinc-500">MediaFileVersion</dt><dd>#{{ $candidate->matchedMediaFileVersion->id }}</dd><dt class="text-zinc-500">Version type</dt><dd>{{ $candidate->matchedMediaFileVersion->version_type->value }}</dd><dt class="text-zinc-500">Media item</dt><dd>#{{ $candidate->matchedMediaFileVersion->media_item_id }}</dd>@endif</dl></article>
</section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Detection contract</h2><div class="mt-5 grid gap-4 md:grid-cols-4 text-sm"><p>match_method=<strong>{{ $candidate->match_method->value }}</strong></p><p>confidence=<strong>{{ $candidate->confidence }}</strong></p><p>review_state=<strong>{{ $candidate->review_state->value }}</strong></p><p>detected_at=<strong>{{ $candidate->detected_at?->format('Y-m-d H:i:s') }}</strong></p></div><p class="mt-5 break-all">matched_sha256=<code>{{ $candidate->matched_sha256 }}</code></p></section>
<section class="rounded-xl border border-emerald-700 bg-emerald-950/30 p-6"><h2 class="text-xl font-semibold text-white">Permanent preservation boundary</h2><p class="mt-3 text-zinc-300">SHA-256 equality records a candidate only. It does not determine provenance, preferred scan, metadata merge, custodianship, deletion or approval.</p><p class="mt-3 text-emerald-200"><strong>No bytes changed. No file removed. No archive record approved. No duplicate decision finalized.</strong></p></section>
</div></x-layouts::app>
