<x-layouts::app :title="__('Duplicate Review Detail')">
<div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-4 md:p-8">
<header><p class="text-sm text-emerald-300">Owner-only / audited manual decision</p><h1 class="text-3xl font-semibold text-white">DC-{{ str_pad((string)$candidate->id, 6, '0', STR_PAD_LEFT) }}</h1><p class="mt-2 text-amber-200">Exact SHA-256 match — human classification required.</p><p class="mt-1 text-sm text-zinc-400">Match method: <code>{{ $candidate->match_method->value }}</code></p></header>
@if(session('status'))<section class="rounded-xl border border-emerald-700 bg-emerald-950/30 p-4 text-emerald-100">{{ session('status') }}</section>@endif
<section class="grid gap-4 lg:grid-cols-2">
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Source upload</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Upload ID</dt><dd>{{ $candidate->incomingUpload->upload_id }}</dd><dt class="text-zinc-500">Retained</dt><dd>{{ $candidate->incomingUpload->source_file_retained ? 'true' : 'false' }}</dd><dt class="text-zinc-500">Duplicate status</dt><dd>{{ $candidate->incomingUpload->duplicate_status->value }}</dd><dt class="text-zinc-500">Review state</dt><dd>{{ $candidate->review_state->value }}</dd></dl></article>
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Exact-match target</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Target type</dt><dd>{{ $candidate->targetType() }}</dd>@if($candidate->matchedIncomingUpload)<dt class="text-zinc-500">Upload ID</dt><dd>{{ $candidate->matchedIncomingUpload->upload_id }}</dd><dt class="text-zinc-500">Retained</dt><dd>{{ $candidate->matchedIncomingUpload->source_file_retained ? 'true' : 'false' }}</dd>@else<dt class="text-zinc-500">MediaFileVersion</dt><dd>#{{ $candidate->matchedMediaFileVersion->id }}</dd><dt class="text-zinc-500">Version type</dt><dd>{{ $candidate->matchedMediaFileVersion->version_type->value }}</dd>@endif</dl></article>
</section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Manual relationship decision</h2><p class="mt-2 text-sm text-zinc-400">Alternate source, related but distinct, and every correction require a reason. Repeating the same decision is idempotent.</p><form method="POST" action="{{ route('admin.duplicate-candidates.resolve', $candidate) }}" class="mt-5 grid gap-4">@csrf<div class="grid gap-3 md:grid-cols-2">@foreach($decisions as $decision)<label class="rounded-lg border border-zinc-700 p-4"><input type="radio" name="decision" value="{{ $decision->value }}" @checked(old('decision', $candidate->resolution?->value) === $decision->value)> <span class="ml-2 text-white">{{ str_replace('_', ' ', $decision->value) }}</span></label>@endforeach</div><label class="text-sm text-zinc-300">Decision note / correction reason<textarea name="reason" rows="3" class="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-white">{{ old('reason') }}</textarea></label>@error('decision')<p class="text-red-300">{{ $message }}</p>@enderror @error('reason')<p class="text-red-300">{{ $message }}</p>@enderror<button class="w-fit rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white">Record audited decision</button></form></section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Immutable decision history</h2><div class="mt-5 space-y-4">@forelse($candidate->reviewEvents as $event)<article class="rounded-lg border border-zinc-700 bg-zinc-950 p-4 text-sm"><p><strong class="text-white">{{ $event->previous_decision?->value ?? 'pending_review' }}</strong> → <strong class="text-emerald-300">{{ $event->new_decision->value }}</strong></p><p class="mt-2 text-zinc-400">Actor: {{ $event->actor->name }} · {{ $event->decided_at?->format('Y-m-d H:i:s') }}</p><p class="mt-2 text-zinc-300">Reason: {{ $event->reason ?? 'No note required.' }}</p></article>@empty<p class="text-zinc-400">No decision event recorded yet.</p>@endforelse</div></section>
<section class="rounded-xl border border-emerald-700 bg-emerald-950/30 p-6"><h2 class="text-xl font-semibold text-white">Permanent preservation boundary</h2><p class="mt-3 text-zinc-300">This decision updates database classification only. It does not choose a preferred scan, attach an alternate source, merge metadata, approve intake, promote an original or generate derivatives.</p><p class="mt-3 text-emerald-200"><strong>No bytes changed. No file removed. No delete or download route exists.</strong></p></section>
</div></x-layouts::app>
