<x-layouts::app :title="__('Incoming Upload Detail')"><div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-4 md:p-8">
@if(session('retained_upload'))<section class="rounded-xl border border-emerald-700 bg-emerald-950/30 p-5 text-emerald-200"><strong>Validated and retained in private quarantine.</strong> Not approved. Not promoted. No derivatives generated.</section>@endif
<header><p class="text-sm text-emerald-300">Read-only IncomingUpload</p><h1 class="text-3xl font-semibold text-white">{{ $upload['upload_id'] }}</h1></header>
<section class="overflow-hidden rounded-xl border border-zinc-700 bg-zinc-950">
<div class="border-b border-zinc-800 px-6 py-4"><p class="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-300">Original source — uncropped</p><p class="mt-1 text-sm text-zinc-400">Inspect the immutable camera original. Crop, rotation, and deskew are generated later as a separate review candidate.</p></div>
<div class="flex min-h-80 items-center justify-center bg-black/40 p-4 md:p-8"><img src="{{ route('admin.photo-intake.preview', $upload['id']) }}" alt="Quarantined photo awaiting owner approval" class="max-h-[70vh] max-w-full rounded-lg object-contain shadow-2xl" loading="eager"></div>
</section>
<section class="grid gap-4 lg:grid-cols-2"><article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Source and technical facts</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Original filename (untrusted)</dt><dd>{{ $upload['original_filename'] }}</dd><dt class="text-zinc-500">Sanitized filename</dt><dd>{{ $upload['sanitized_filename'] }}</dd><dt class="text-zinc-500">Detected MIME</dt><dd>{{ $upload['mime_type'] }}</dd><dt class="text-zinc-500">Extension</dt><dd>{{ $upload['extension'] }}</dd><dt class="text-zinc-500">Exact byte count</dt><dd>{{ number_format($upload['size_bytes']) }}</dd><dt class="text-zinc-500">Dimensions</dt><dd>{{ $upload['dimensions'] }}</dd></dl></article>
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Verified quarantine retention</h2><p class="mt-4 text-zinc-400">Logical disk</p><code class="text-emerald-300">{{ $upload['logical_disk'] }}</code><p class="mt-4 text-zinc-400">Relative path only</p><code class="break-all">{{ $upload['incoming_path'] }}</code><div class="mt-5 grid grid-cols-2 gap-3 text-sm"><p><strong>retained={{ $upload['source_file_retained'] ? 'true' : 'false' }}</strong></p><p>integrity=<strong>{{ $upload['integrity_status'] }}</strong></p><p class="col-span-2">retained_at=<strong>{{ $upload['retained_at'] ?? 'null' }}</strong></p></div></article></section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Integrity and archive boundary</h2><p class="mt-4 break-all">SHA-256: <strong>{{ $upload['sha256'] ?? 'null' }}</strong></p><div class="mt-5 grid gap-3 md:grid-cols-4 text-sm"><p>Perceptual hash: <strong>{{ $upload['perceptual_hash'] ?? 'null' }}</strong></p><p>Archive link: <strong>{{ $upload['media_item_id'] ?? 'null' }}</strong></p><p>Review: <strong>{{ $upload['review_status'] }}</strong></p><p>Duplicate: <strong>{{ $upload['duplicate_status'] }}</strong></p></div>
@if($upload['media_item_id'])
<p class="mt-5 text-emerald-200">The immutable original is approved and retained. {{ $processingJob?->candidate ? 'A separate candidate is ready for human review.' : 'No candidate has been generated.' }}</p>
<a href="{{ route('admin.restoration', $processingJob?->candidate ? ['candidate' => $processingJob->candidate->id] : []) }}" class="mt-4 inline-flex rounded-lg bg-white px-4 py-2 font-semibold text-zinc-950">Open restoration review</a>
@else
<div class="mt-5 rounded-lg border border-amber-800 bg-amber-950/20 p-4 text-amber-100">
<p class="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">Step 1 of 2 · Accept the source</p>
<p class="mt-2">Not approved until this step completes. Verify the uncropped source, preserve it as the immutable original, then generate a separate edit preview. You will be taken directly to a side-by-side comparison before the edit can become the viewing version.</p>
</div>
@if($submission)
<div class="mt-4 rounded-lg border border-zinc-700 bg-zinc-950 p-4 text-sm"><p class="font-semibold text-white">Uploader automation controls</p><p class="mt-2 text-zinc-400">Mode: {{ data_get($submission->automation_preferences, 'automation_mode', 'suggestions') }} · Crop: {{ data_get($submission->automation_preferences, 'crop_target', 'none') }} · Auto-rotate: {{ data_get($submission->automation_preferences, 'auto_rotate', false) ? 'on' : 'off' }} · Deskew: {{ data_get($submission->automation_preferences, 'deskew', false) ? 'on' : 'off' }}</p></div>
@endif
<form method="POST" action="{{ route('admin.photo-intake.approve-and-process', $upload['id']) }}" class="mt-5">@csrf<button type="submit" class="rounded-lg bg-emerald-400 px-5 py-3 font-semibold text-zinc-950">Accept original and generate edit preview</button></form>
@endif
</section>
</div></x-layouts::app>
