<?php

use App\Domain\Archive\Enums\ArchiveStorageDisk;
use App\Domain\Media\Enums\MediaFileVersionType;
use App\Domain\Media\Enums\MediaType;

return [
    'bucket_size' => 1000,
    'prefixes' => [MediaType::Photo->value => 'PH', MediaType::Video->value => 'VD', MediaType::Document->value => 'DC', MediaType::Audio->value => 'AU', MediaType::Other->value => 'OT'],
    'media_segments' => [MediaType::Photo->value => 'photos', MediaType::Video->value => 'videos', MediaType::Document->value => 'documents', MediaType::Audio->value => 'audio', MediaType::Other->value => 'other'],
    'disks' => [
        ArchiveStorageDisk::Originals->value => ['purpose' => 'Approved original media', 'private' => true, 'public_url' => false],
        ArchiveStorageDisk::Derivatives->value => ['purpose' => 'Rebuildable edited and viewing files', 'private' => true, 'public_url' => false],
        ArchiveStorageDisk::Quarantine->value => ['purpose' => 'Incoming, failed and possible-duplicate files', 'private' => true, 'public_url' => false],
        ArchiveStorageDisk::Manifests->value => ['purpose' => 'Future integrity and recovery manifests', 'private' => true, 'public_url' => false],
    ],
    'version_segments' => [
        MediaFileVersionType::EditedFull->value => 'edited-full', MediaFileVersionType::WebDisplay->value => 'web-display', MediaFileVersionType::Thumbnail->value => 'thumbnails',
        MediaFileVersionType::VideoStream->value => 'video-stream', MediaFileVersionType::VideoPreview->value => 'video-preview', MediaFileVersionType::DocumentPreview->value => 'document-preview',
    ],
    'photo_derivatives' => [
        'memory_limit' => env('ARCHIVE_PHOTO_DERIVATIVE_MEMORY_LIMIT', '512M'),
        'max_source_bytes' => 104857600,
        'max_source_pixels' => 80000000,
        'imagemagick_path' => env('ARCHIVE_PHOTO_DERIVATIVE_IMAGEMAGICK_PATH', PHP_OS_FAMILY === 'Windows' ? '' : '/usr/local/bin/magick'),
        'imagemagick_minimum_source_pixels' => (int) env('ARCHIVE_PHOTO_DERIVATIVE_IMAGEMAGICK_MINIMUM_SOURCE_PIXELS', 30000000),
        'imagemagick_memory_limit' => env('ARCHIVE_PHOTO_DERIVATIVE_IMAGEMAGICK_MEMORY_LIMIT', '64MiB'),
        'imagemagick_map_limit' => env('ARCHIVE_PHOTO_DERIVATIVE_IMAGEMAGICK_MAP_LIMIT', '128MiB'),
        'imagemagick_disk_limit' => env('ARCHIVE_PHOTO_DERIVATIVE_IMAGEMAGICK_DISK_LIMIT', '8GiB'),
        'imagemagick_timeout_seconds' => (int) env('ARCHIVE_PHOTO_DERIVATIVE_IMAGEMAGICK_TIMEOUT_SECONDS', 900),
        'targets' => [
            MediaFileVersionType::WebDisplay->value => ['max_long_side' => 2000, 'quality' => 82],
            MediaFileVersionType::Thumbnail->value => ['max_long_side' => 480, 'quality' => 72],
        ],
    ],
    'photo_intake' => [
        'max_bytes' => 104857600,
        'max_width' => 40000,
        'max_height' => 40000,
        'max_pixels' => 250000000,
        'mime_extensions' => [
            'image/jpeg' => ['jpg', 'jpeg'], 'image/png' => ['png'], 'image/webp' => ['webp'], 'image/tiff' => ['tif', 'tiff'],
        ],
    ],
    'batch_preflight' => [
        'derivative_reserve_ratio' => (float) env('ARCHIVE_BATCH_DERIVATIVE_RESERVE_RATIO', 0.45),
        'working_reserve_ratio' => (float) env('ARCHIVE_BATCH_WORKING_RESERVE_RATIO', 0.15),
        'maximum_unattended_chunks' => (int) env('ARCHIVE_BATCH_MAXIMUM_UNATTENDED_CHUNKS', 1000),
    ],
    'restoration' => [
        'memory_limit' => env('ARCHIVE_RESTORATION_MEMORY_LIMIT', '512M'),
        'max_source_pixels' => (int) env('ARCHIVE_RESTORATION_MAX_SOURCE_PIXELS', 24000000),
        'minimum_crop_confidence' => (float) env('ARCHIVE_MINIMUM_CROP_CONFIDENCE', 0.72),
        'minimum_crop_boundary_inset' => (float) env('ARCHIVE_MINIMUM_CROP_BOUNDARY_INSET', 0.015),
        'minimum_crop_area_ratio' => (float) env('ARCHIVE_MINIMUM_CROP_AREA_RATIO', 0.45),
        'maximum_crop_aspect_ratio_delta' => (float) env('ARCHIVE_MAXIMUM_CROP_ASPECT_RATIO_DELTA', 0.32),
        'maximum_crop_margin_balance' => (float) env('ARCHIVE_MAXIMUM_CROP_MARGIN_BALANCE', 0.28),
    ],
    'multi_photo' => [
        'max_source_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_MAX_SOURCE_PIXELS', 250000000),
        'minimum_seam_spacing' => (float) env('ARCHIVE_MULTI_PHOTO_MINIMUM_SEAM_SPACING', 0.08),
        'maximum_axis_seams' => (int) env('ARCHIVE_MULTI_PHOTO_MAXIMUM_AXIS_SEAMS', 7),
        'maximum_regions' => (int) env('ARCHIVE_MULTI_PHOTO_MAXIMUM_REGIONS', 32),
        'automatic_review' => [
            'maximum_regions' => (int) env('ARCHIVE_MULTI_PHOTO_AUTOMATIC_MAXIMUM_REGIONS', 10),
            'minimum_region_area_basis_points_squared' => (int) env('ARCHIVE_MULTI_PHOTO_AUTOMATIC_MINIMUM_REGION_AREA', 2000000),
            'minimum_two_region_area_basis_points_squared' => (int) env('ARCHIVE_MULTI_PHOTO_AUTOMATIC_MINIMUM_TWO_REGION_AREA', 25000000),
            'minimum_single_axis_span_basis_points' => (int) env('ARCHIVE_MULTI_PHOTO_AUTOMATIC_MINIMUM_SINGLE_AXIS_SPAN', 1000),
        ],
        'candidate_rendering' => [
            'memory_limit' => env('ARCHIVE_MULTI_PHOTO_MEMORY_LIMIT', '512M'),
            'imagemagick_path' => env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_PATH', PHP_OS_FAMILY === 'Windows' ? '' : '/usr/local/bin/magick'),
            'imagemagick_minimum_source_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_MINIMUM_SOURCE_PIXELS', 45000001),
            'imagemagick_max_source_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_MAX_SOURCE_PIXELS', 250000000),
            'imagemagick_memory_limit' => env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_MEMORY_LIMIT', '64MiB'),
            'imagemagick_map_limit' => env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_MAP_LIMIT', '128MiB'),
            'imagemagick_disk_limit' => env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_DISK_LIMIT', '8GiB'),
            'imagemagick_timeout_seconds' => (int) env('ARCHIVE_MULTI_PHOTO_IMAGEMAGICK_TIMEOUT_SECONDS', 900),
            'sharp_node_path' => env('ARCHIVE_MULTI_PHOTO_SHARP_NODE_PATH', PHP_OS_FAMILY === 'Windows' ? '' : '/usr/local/bin/node'),
            'sharp_minimum_source_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_SHARP_MINIMUM_SOURCE_PIXELS', 30000000),
            'sharp_minimum_region_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_SHARP_MINIMUM_REGION_PIXELS', 6000000),
            'sharp_max_source_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_SHARP_MAX_SOURCE_PIXELS', 250000000),
            'sharp_max_output_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_SHARP_MAX_OUTPUT_PIXELS', 24000000),
            'sharp_max_working_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_SHARP_MAX_WORKING_PIXELS', 6000000),
            'sharp_apply_deskew' => (bool) env('ARCHIVE_MULTI_PHOTO_SHARP_APPLY_DESKEW', false),
            'sharp_timeout_seconds' => (int) env('ARCHIVE_MULTI_PHOTO_SHARP_TIMEOUT_SECONDS', 900),
            'padding_ratio' => (float) env('ARCHIVE_MULTI_PHOTO_PADDING_RATIO', 0.08),
            'minimum_padding_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_MINIMUM_PADDING_PIXELS', 8),
            'maximum_padding_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_MAXIMUM_PADDING_PIXELS', 192),
            'final_safety_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_FINAL_SAFETY_PIXELS', 2),
            'minimum_deskew_confidence' => (float) env('ARCHIVE_MULTI_PHOTO_MINIMUM_DESKEW_CONFIDENCE', 0.55),
            'minimum_deskew_degrees' => (float) env('ARCHIVE_MULTI_PHOTO_MINIMUM_DESKEW_DEGREES', 0.4),
            'maximum_deskew_degrees' => (float) env('ARCHIVE_MULTI_PHOTO_MAXIMUM_DESKEW_DEGREES', 8.0),
            'webp_quality' => (int) env('ARCHIVE_MULTI_PHOTO_WEBP_QUALITY', 90),
            'quality_minimum_dimension_pixels' => (int) env('ARCHIVE_MULTI_PHOTO_QUALITY_MINIMUM_DIMENSION', 160),
            'quality_maximum_transparent_edge_ratio' => (float) env('ARCHIVE_MULTI_PHOTO_QUALITY_MAXIMUM_TRANSPARENT_EDGE_RATIO', 0.20),
            'quality_minimum_detail_score' => (float) env('ARCHIVE_MULTI_PHOTO_QUALITY_MINIMUM_DETAIL_SCORE', 2.0),
        ],
        'grid' => [
            'minimum_confidence' => (float) env('ARCHIVE_MULTI_PHOTO_GRID_MINIMUM_CONFIDENCE', 0.77),
            'minimum_coverage' => (float) env('ARCHIVE_MULTI_PHOTO_GRID_MINIMUM_COVERAGE', 0.78),
            'minimum_difference' => (float) env('ARCHIVE_MULTI_PHOTO_GRID_MINIMUM_DIFFERENCE', 40),
            'minimum_gutter' => (float) env('ARCHIVE_MULTI_PHOTO_GRID_MINIMUM_GUTTER', 0.78),
        ],
        'single' => [
            'minimum_confidence' => (float) env('ARCHIVE_MULTI_PHOTO_SINGLE_MINIMUM_CONFIDENCE', 0.88),
            'minimum_coverage' => (float) env('ARCHIVE_MULTI_PHOTO_SINGLE_MINIMUM_COVERAGE', 0.92),
            'minimum_difference' => (float) env('ARCHIVE_MULTI_PHOTO_SINGLE_MINIMUM_DIFFERENCE', 62),
            'minimum_gutter' => (float) env('ARCHIVE_MULTI_PHOTO_SINGLE_MINIMUM_GUTTER', 0.90),
        ],
    ],
];
