<x-layouts::app :title="__('Viewing Derivatives')"><div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-4 md:p-8">
<header><p class="text-sm text-emerald-300">Owner-only / safe viewing derivatives</p><h1 class="text-3xl font-semibold text-white">{{ $mediaItem->archive_id }}</h1><p class="mt-2 text-zinc-400">Private photo-v1 WebP generation with verified lineage.</p></header>
@if(session('status'))<section class="rounded-xl border border-emerald-700 bg-emerald-950/30 p-5 text-emerald-100">{{ session('status') }}</section>@endif
<section class="rounded-xl border border-amber-700 bg-amber-950/30 p-5 text-amber-100"><strong>Permanent derivative boundary:</strong> original bytes, path, hash and metadata remain untouched. No edited-full copy, no upscaling, no original preview and no original download are created.</section>
@if($original)
<section class="grid gap-4 lg:grid-cols-2"><article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Verified preferred original</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Version</dt><dd>#{{ $original->id }} / original</dd><dt class="text-zinc-500">State</dt><dd>{{ $original->generation_status->value }}</dd><dt class="text-zinc-500">Dimensions</dt><dd>{{ $original->width }} × {{ $original->height }}</dd><dt class="text-zinc-500">Exact bytes</dt><dd>{{ number_format($original->file_size_bytes) }}</dd><dt class="text-zinc-500">SHA-256</dt><dd class="break-all">{{ $original->sha256 }}</dd><dt class="text-zinc-500">Original mutation</dt><dd>none</dd></dl></article>
<article class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">photo-v1 recipe</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-500">Web display</dt><dd>WebP · longest side ≤ 2000 · quality 82</dd><dt class="text-zinc-500">Thumbnail</dt><dd>WebP · longest side ≤ 480 · quality 72</dd><dt class="text-zinc-500">Upscaling</dt><dd>never</dd><dt class="text-zinc-500">Orientation</dt><dd>applied to render only</dd><dt class="text-zinc-500">Metadata</dt><dd>EXIF / GPS / XMP / client filename stripped</dd><dt class="text-zinc-500">Storage</dt><dd>private archive_derivatives / no overwrite</dd></dl></article></section>
@if(!$webDisplay || !$thumbnail)
<section class="rounded-xl border {{ $eligible ? 'border-emerald-700' : 'border-red-800' }} bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Generation decision</h2>@if($eligible)<p class="mt-3 text-emerald-200">Eligible: approved photo, ready preferred original and exact source integrity verified.</p><form method="POST" action="{{ route('admin.viewing-derivatives.store', $mediaItem) }}" class="mt-5">@csrf<button class="rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white">Generate and verify private viewing copies</button></form>@else<p class="mt-3 text-red-300">Not eligible. Generation fails closed and creates no derivative object or row.</p>@endif</section>
@endif
@if($webDisplay || $thumbnail)
<section class="grid gap-4 lg:grid-cols-2">
@if($webDisplay)<article class="rounded-xl border border-emerald-700 bg-emerald-950/20 p-6"><h2 class="text-xl font-semibold text-white">Web display derivative</h2><img class="mt-5 max-h-80 w-full rounded-lg bg-black object-contain" src="{{ route('admin.viewing-derivatives.preview', $webDisplay) }}" alt="Private generated web display"><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-400">Version</dt><dd>#{{ $webDisplay->id }} / web_display</dd><dt class="text-zinc-400">Parent</dt><dd>original #{{ $webDisplay->parent_version_id }}</dd><dt class="text-zinc-400">Format</dt><dd>WebP</dd><dt class="text-zinc-400">Dimensions</dt><dd>{{ $webDisplay->width }} × {{ $webDisplay->height }}</dd><dt class="text-zinc-400">Quality / recipe</dt><dd>{{ $webDisplay->generation_recipe['quality'] }} / {{ $webDisplay->generation_recipe['recipe_version'] }}</dd><dt class="text-zinc-400">State</dt><dd>ready / preferred</dd><dt class="text-zinc-400">Metadata policy</dt><dd>pixels only</dd></dl></article>@endif
@if($thumbnail)<article class="rounded-xl border border-emerald-700 bg-emerald-950/20 p-6"><h2 class="text-xl font-semibold text-white">Thumbnail derivative</h2><img class="mt-5 max-h-80 w-full rounded-lg bg-black object-contain" src="{{ route('admin.viewing-derivatives.preview', $thumbnail) }}" alt="Private generated thumbnail"><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-zinc-400">Version</dt><dd>#{{ $thumbnail->id }} / thumbnail</dd><dt class="text-zinc-400">Parent</dt><dd>original #{{ $thumbnail->parent_version_id }}</dd><dt class="text-zinc-400">Format</dt><dd>WebP</dd><dt class="text-zinc-400">Dimensions</dt><dd>{{ $thumbnail->width }} × {{ $thumbnail->height }}</dd><dt class="text-zinc-400">Quality / recipe</dt><dd>{{ $thumbnail->generation_recipe['quality'] }} / {{ $thumbnail->generation_recipe['recipe_version'] }}</dd><dt class="text-zinc-400">No upscale</dt><dd>{{ $thumbnail->generation_recipe['no_upscale'] ? 'true' : 'false' }}</dd><dt class="text-zinc-400">State</dt><dd>ready / preferred</dd></dl></article>@endif
</section>
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Original and lineage preserved</h2><p class="mt-3 text-emerald-200">Both derivative records point to original #{{ $original->id }}. Source SHA-256 in each recipe matches the unchanged original. No edited_full record exists.</p></section>
@endif
@endif
<section class="rounded-xl border border-zinc-700 bg-zinc-900 p-6"><h2 class="text-xl font-semibold text-white">Access and exposure boundary</h2><p class="mt-3 text-zinc-400">Derivative previews are authenticated and private. They never fall back to the original and disclose no original disk, path, source filename or original-download route.</p></section>
</div></x-layouts::app>
