name: code-scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '23 18 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codeql:
    name: codeql (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: read
    strategy:
      fail-fast: false
      matrix:
        language:
          - actions
          - javascript-typescript

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@bce182f857edf1feab116e9795a3393d21977282 # v4
        with:
          languages: ${{ matrix.language }}

      - name: Analyze
        uses: github/codeql-action/analyze@bce182f857edf1feab116e9795a3393d21977282 # v4
        with:
          category: /language:${{ matrix.language }}
